### ISSUE TITLE
Error on line 21 T_FUNCTION

### ISSUE THREAD

**Issue by reggi** [notmaintained/shopify.php#2]
So I just plopped in the code and included it and I'm getting an error right out the gate.

Parse error: syntax error, unexpected T_FUNCTION in *******/shopify.php on line 21

I believe it is refering to that return anonymous function which is something I've personally never seen before, any ideas on why I'm getting this error?

I am using a pretty up to date version of PHP on dreamhost.

**Comment by reggi** [comment]
I just read up on anonymous functions in php (http://php.net/manual/en/functions.anonymous.php) it states "Note: Anonymous functions are available since PHP 5.3.0". Just checked dreamhost and didn't realize I was running 5.2.0. I'm reconfiguring dreamhost now I'll give some feedback on if this fixes the issue. If not I guess I'll used this version https://github.com/cmcdonaldca/ohShopify.php

**Comment by reggi** [comment]
It works!! Yay for solving a non-issue all on my own. =]

**Comment by sandeepshetty** [comment]
:)
