### ISSUE TITLE
oAuth 2.0

### ISSUE THREAD

**Issue by reggi** [notmaintained/shopify.php#3]
Shopify will be switching to oAuth 2.0 is there any prospect of updating the library?

http://www.shopify.com/technology/5922341-sound-the-trumpets-oauth2-has-arrived

**Comment by sandeepshetty** [comment]
Will try to get this done by tomorrow. Feel free to send me a pull request.

**Comment by cmcdonaldca** [comment]
Hey reggi, I based ohShopify off this adapter and have already updated it to oAuth 2.0.  You could take a look at my changes and probably get this working for sandeep's version pretty quickly.  There are only a few small changes:

https://github.com/cmcdonaldca/ohShopify.php/blob/870d6ddff6a723fedcedecba247839aec5288a59/shopify.php

**Comment by mobweb** [comment]
Has any progress been made on this? I tried myself but always failed at some point or another.

**Comment by cmcdonaldca** [comment]
you can use "ohShopify" until Sandeep or anyone else get's this going.

https://github.com/cmcdonaldca/ohShopify.php/blob/master/shopify.php

and here is an example of it working:

https://github.com/cmcdonaldca/ohShopify-Sample-App

**Comment by sandeepshetty** [comment]
I wanted to extract the curl bits out before putting in the oAuth 2 changes. Got that done a few days ago:
https://github.com/sandeepshetty/wcurl

Now onto the oAuth 2.0 changes. Should have something within 48 hrs. in the meantime, if you prefer an OO wrapper, you can try @cmcdonaldca's version mentioned in the previous comment.

**Comment by reggi** [comment]
wcurl looks pretty awesome

**Comment by sandeepshetty** [comment]
I've created a new repo for the oAuth2 lib:
https://github.com/sandeepshetty/shopify_client/

WIP but usable. Try it out and let me know what you think.

In the short term I might be adding a namespace and will try to add legacy auth support as well.

**Comment by sandeepshetty** [comment]
Repo was renamed and it's now available at:
https://github.com/sandeepshetty/shopify_api

**Comment by ghost** [comment]
I am using ohShopify. Is authorize.php deprecated with oauth? Im getting the Oauth error invalid_request: The redirect_uri is missing or not whitelisted error
